
  
name: Lowlighter Metrics

on:
  schedule:
    # 12AM EST (midnight)
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    if: "github.repository == 'Nathan13888/Nathan13888'"
    steps:
      - name: 📗 Classic template
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.GH_TOKEN }}# ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          plugins_errors_fatal: ${{ github.repository == 'Nathan13888/Nathan13888' }}
          output_action: pull-request
          delay: 120
          
      - name: 🏆 Achievements
        uses: lowlighter/metrics@latest
        with:
          plugin_achievements: yes
          plugin_achievements_threshold: B       # Display achievements with rank B or higher
          plugin_achievements_secrets: yes       # Display unlocked secrets achievements
          plugin_achievements_ignored: octonaut  # Hide octonaut achievement
          plugin_achievements_limit: 0           # Display all unlocked achievement matching threshold and secrets params

      - name: 📅 Isocalendar plugin
        uses: lowlighter/metrics@latest
        with:
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
      
      - name: 🎭 Reactions plugin
        uses: lowlighter/metrics@latest
        with:
          plugin_reactions: yes
          plugin_reactions_limit: 200                 # Compute reactions over last 200 issue comments
          plugin_reactions_limit_issues: 100          # Compute reactions over last 100 issues/pull requests opened
          plugin_reactions_days: 14                   # Compute reactions on issue comments posted less than 14 days ago
          plugin_reactions_details: count, percentage # Display reactions count and percentage
          plugin_reactions_ignored: bot               # Ignore "bot" user
        
      - name: ⏰ WakaTime plugin
        uses: lowlighter/metrics@latest
        with:
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }} #${{ secrets.WAKATIME_TOKEN }}      # Required
          plugin_wakatime_days: 7                                   # Display last week stats
          plugin_wakatime_sections: time, projects, projects-graphs # Display time and projects sections, along with projects graphs
          plugin_wakatime_limit: 4                                  # Show 4 entries per graph
          plugin_wakatime_url: https://wakatime.com                 # Wakatime url endpoint
          plugin_wakatime_user: Nathan13888                         # User
